// Default model options
// https://sequelize.org/master/class/lib/model.js~Model.html#static-method-init

module.exports = {
	freezeTableName: true,		// use model name as table name
	createdAt: "created_at",	// override name for autogenerated attribute
	updatedAt: "updated_at",	// override name for autogenerated attribute
};
